catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from catalog.views import CategoryListView, ContactsTemplateView, ProductListView, ProductDetailView, ArticleListView, \
    ArticleCreateView, ArticleUpdateView, ArticleDetailView, ArticleDeleteView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    # Category
    path('', CategoryListView.as_view(), name='home'),

    # Contacts
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),

    # Products
    path('products/', ProductListView.as_view(), name='products'),
    path('product/<int:pk>/', cache_page(60 * 2)(ProductDetailView.as_view()), name='product_item'),
    path('products/create/', never_cache(ProductCreateView.as_view()), name='product_create'),
    path('products/edit/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='product_edit'),
    path('products/delete/<int:pk>/', never_cache(ProductDeleteView.as_view()), name='product_delete'),

    # Articles
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('create/', never_cache(ArticleCreateView.as_view()), name='create'),
    path('article/edit/<slug:slug>/', never_cache(ArticleUpdateView.as_view()), name='article_edit'),
    path('articles/<slug:slug>/', ArticleDetailView.as_view(), name='article'),
    path('article/delete/<slug:slug>/', never_cache(ArticleDeleteView.as_view()), name='article_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # Apps
    path('', include('catalog.urls', namespace='catalog')),

    # Users
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, VerifyEmailView, LogoutUserView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verify_email/<str:token>/', VerifyEmailView.as_view(), name='verify_email'),
]

catalog/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(default='default_description', verbose_name='Описание')
    image = models.ImageField(upload_to='products/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория')
    price = models.PositiveIntegerField(verbose_name='Цена')
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    last_modification_date = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')

    owner_product = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        verbose_name='Создатель продукта',
        **NULLABLE
    )

    is_published = models.BooleanField(default=False, verbose_name='Признак публикации')

    def __str__(self):
        return f'{self.name}, {self.price}, {self.category}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('id',)
        # Задаем новые права доступа (ко всей модели и всем полям модели)
        permissions = [
            (
                'set_published',
                'Can change is_published, description, category'
            )
        ]


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(default='default_description', verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('id',)


class Article(models.Model):
    title = models.CharField(max_length=300, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, verbose_name='Slug', **NULLABLE)
    content = models.TextField(max_length=10000, verbose_name='Содержание')
    preview = models.ImageField(upload_to='article/', verbose_name='Превью', **NULLABLE)
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации')
    number_of_views = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ('id',)


class Version(models.Model):
    product = models.ForeignKey(
        'Product',
        on_delete=models.CASCADE,
        verbose_name='Продукт',
        related_name='versions'
    )
    version_number = models.CharField(max_length=50, verbose_name='Номер версии')
    name = models.CharField(max_length=150, verbose_name='Название версии')
    is_active = models.BooleanField(default=False, verbose_name='Признак текущей версии')

    def __str__(self):
        return f'{self.name} {self.version_number}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'
        ordering = ('id',)

catalog/forms.py
from django import forms

from catalog.models import Product, Version

STOP_LIST = [
    'казино',
    'криптовалюта',
    'крипта',
    'биржа',
    'дешево',
    'бесплатно',
    'обман',
    'полиция',
    'радар'
]


class StyleFormMixin():
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForUserForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('creation_date', 'last_modification_date', 'owner_product', 'is_published')

    def clean_text(self, field_name):
        cleaned_data = self.cleaned_data[field_name].lower()

        for word in STOP_LIST:
            if word in cleaned_data:
                raise forms.ValidationError(f'{field_name.capitalize()} продукта не допустимо!')
            else:
                cleaned_data = self.cleaned_data[field_name]

        return cleaned_data

    def clean_name(self):
        return self.clean_text('name')

    def clean_description(self):
        return self.clean_text('description')


class ProductForManagerForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('is_published', 'description', 'category',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Добавление чекбокса для is_published
        self.fields['is_published'].widget = forms.CheckboxInput()

    def clean_text(self, field_name):
        cleaned_data = self.cleaned_data[field_name].lower()

        for word in STOP_LIST:
            if word in cleaned_data:
                raise forms.ValidationError(f'{field_name.capitalize()} продукта не допустимо!')
            else:
                cleaned_data = self.cleaned_data[field_name]

        return cleaned_data

    def clean_description(self):
        return self.clean_text('description')


class VersionForm(forms.ModelForm):
    version_number = forms.CharField(
        label='Номер версии',
        widget=forms.TextInput(attrs={'placeholder': 'Укажите номер',
                                      'class': 'form-control'})
    )
    name = forms.CharField(
        label='Название версии',
        widget=forms.TextInput(attrs={'placeholder': 'Укажите название',
                                      'class': 'form-control'})
    )
    is_active = forms.BooleanField(
        label='Признак текущей версии',
        required=False,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'})

    )

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404, HttpResponseForbidden
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, TemplateView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from catalog.forms import ProductForUserForm, ProductForManagerForm, VersionForm
from catalog.models import Category, Product, Article, Version
from catalog.services.view_services import get_cached_categories


class CategoryListView(ListView):
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        context_data['object_list'] = get_cached_categories()

        return context_data


class ContactsTemplateView(TemplateView):
    template_name = 'catalog/contacts.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        if self.request.method == "POST":
            name = self.request.POST.get('name')
            phone = self.request.POST.get('phone')
            message = self.request.POST.get('message')
            print(f'You have new message from {name}, phone: {phone} message: {message}')

        return context_data


class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()

        # Проверяем, зарегистрирован ли пользователь
        if not self.request.user.is_authenticated:
            return queryset.filter(is_published=True)

        # Если пользователь является создателем статей (user_product - группа)
        if self.request.user.has_perm('catalog.add_product'):
            current_user = self.request.user
            # Фильтруем продукты по is_published и owner_product
            return queryset.filter(is_published=True, owner_product=current_user)

        # Если пользователь is_staff=True, то отображаем все продукты без исключения.
        if self.request.user.is_staff:
            return queryset

        return queryset


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product


class ArticleListView(ListView):
    model = Article

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)

        queryset = queryset.filter(is_published=True)

        return queryset


class ArticleCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Article
    fields = ('title', 'content', 'preview', 'is_published',)
    success_url = reverse_lazy('catalog:articles')
    permission_required = 'catalog.add_article'

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            # Работа со слагом
            new_article.slug = slugify(new_article.title)
            new_article.save()

        return super().form_valid(form)


class ArticleUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Article
    fields = ('title', 'content', 'preview', 'is_published',)
    permission_required = 'catalog.change_article'

    def get_success_url(self):
        return reverse('catalog:article', args=[self.kwargs.get('slug')])

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            # Работа со слагом
            new_article.slug = slugify(new_article.title)
            new_article.save()

        return super().form_valid(form)


class ArticleDetailView(LoginRequiredMixin, DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        # Увеличение счетчика просмотров
        self.object.number_of_views += 1
        self.object.save()

        return self.object


class ArticleDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('catalog:articles')
    permission_required = 'catalog.delete_article'


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForUserForm
    permission_required = 'catalog.add_product'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        # Формсет
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, self.request.FILES)
        else:
            context_data['formset'] = VersionFormset()

        return context_data

    def get_success_url(self):
        return reverse('catalog:product_item', args=[self.object.pk])

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()

        # Присваиваем продукту в качестве владельца текущего пользователя.
        self.object.owner_product = self.request.user
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    permission_required = 'catalog.change_product'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        # Если пользователь is_staff можно редактировать
        if self.request.user.is_staff:
            return self.object

        # Вызывает ошибку если текущий пользователь не владелец продукта.
        if self.object.owner_product != self.request.user:
            raise HttpResponseForbidden

        return self.object

    def get_form_class(self, *args, **kwargs):
        if self.request.user == self.object.owner_product:
            # Вернуть форму ProductForUserForm для создателя продукта.
            return ProductForUserForm
        elif self.request.user.is_staff and self.request.user.has_perm('catalog.set_published'):
            # Вернуть форму ProductForManagerForm для менеджера.
            return ProductForManagerForm
        else:
            # Вызвать 404 ошибку если ни одно условие не подошло.
            raise Http404

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        # Формсет
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)

        return context_data

    def get_success_url(self):
        return reverse('catalog:product_item', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()

        # Присваиваем продукту в качестве владельца текущего пользователя.
        self.object.owner_product = self.request.user
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:products')
    permission_required = 'catalog.delete_product'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        # Вызывает ошибку 404 если текущий пользователь не владелец продукта.
        if self.object.owner_product != self.request.user:
            raise HttpResponseForbidden

        return self.object

catalog/templates/catalog/article_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <p class="card-text">
                    Хотите удалить статью? "{{ object.title }}"</p>
                <button type="submit" class="btn btn-danger mb-3" style="margin-left: 50px;">
                    Удалить
                </button>
                <a class="p-2 btn btn-warning mb-3" href="{% url 'catalog:articles' %}" style="margin-left: 50px;">Отмена</a>
            </form>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/article_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <p class="card-text">Дата публикации: {{ object.creation_date }}</p>
            <p class="card-text">Количество просмотров: {{ object.number_of_views }}</p>
            <h5 class="card-title">{{ object.title }}</h5>
            <p class="card-text">{{ object.content }}</p>
        </div>
    </div>
    <div class="pricing-header px-2 py-2 pt-md-2 pb-md-2 mx-auto text-left">
        {% if perms.catalog.change_article %}
        <a class="btn btn-lg btn-primary" style="margin-left: 600px;"
           href="{% url 'catalog:article_edit' object.slug %}">Редактировать статью</a>
        {% endif %}
        {% if perms.catalog.delete_article %}
        <a class="btn btn-lg btn-danger" href="{% url 'catalog:article_delete' object.slug %}">Удалить статью</a>
        {% endif %}
    </div>
    {% endblock %}

catalog/templates/catalog/article_form.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    {% if object %}
                        Сохранить
                    {% else %}
                        Создать
                    {% endif %}
                </button>
            </form>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/article_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Статьи</h1>
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-left">
    {% if perms.catalog.add_article %}
        <a class="btn btn-lg btn-primary" style="margin-left: 102px;" href="{% url 'catalog:create' %}">Добавить статью</a>
    {% endif %}
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-6">
            <div class="card mb-4 box-shadow" style="height: 700px;">
                <div class="card-header">
                    <img src="/media/{{ object.preview }}" style="max-width: 550%; height: auto;" class="card-img-bottom">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body d-flex flex-column">
                    <div class="mt-auto">
                        <p class="card-title pricing-card-title" style="text-align: left;">{{ object.content|slice:":340" }}...</p>
                    </div>
                    <div class="mt-auto">
                        <a href="{% url 'catalog:article' object.slug %}" class="btn btn-lg btn-block btn-outline-primary">Читать</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_catalog_menu.html' %}

{% block content %}
{% endblock %}
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="container">
        <div class="row">
            <div class="col-3 col-md">
                <small class="d-block mb-3 text-muted">{{ user.email|default:"Вы не авторизованны" }}</small>
            </div>
            <div class="col-3 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                </ul>
            </div>
            <div class="col-3 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:articles' %}">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-3 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

<script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Все категории</h1>
    <p class="lead">Skystore - это отличный вариант приобретения плагинов, проектов и других IT-услуг.</p>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow" style="height: 320px;">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body d-flex flex-column">
                    <div class="mt-auto">
                        <p class="card-title pricing-card-title" style="text-align: left;">{{ object.description }}</p>
                    </div>
                    <div class="mt-auto">
                        <a href="{% url 'catalog:products' %}" class="btn btn-lg btn-block btn-outline-primary">Выбрать</a>
                    </div>
                </div>
            </div>

        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond, WA, 98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение нам" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Все категории</h1>
    <p class="lead">Skystore - это отличный вариант приобретения плагинов, проектов и других IT-услуг.</p>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow" style="height: 320px;">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body d-flex flex-column">
                    <div class="mt-auto">
                        <p class="card-title pricing-card-title" style="text-align: left;">{{ object.description }}</p>
                    </div>
                    <div class="mt-auto">
                        <a href="{% url 'catalog:products' %}" class="btn btn-lg btn-block btn-outline-primary">Выбрать</a>
                    </div>
                </div>
            </div>

        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p class="card-text">
                            Хотите удалить продукт? "{{ object.name }}"</p>
                        <button type="submit" class="btn btn-danger mb-3" style="margin-left: 50px;">
                            Удалить
                        </button>
                        <a class="p-2 btn btn-warning mb-3" href="{% url 'catalog:product_item' object.pk %}"
                           style="margin-left: 50px;">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="container">
    <div class="row-12">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        <h5 class="card-title">{{ object.name }}</h5>
                    </h3>
                </div>
                <div class="card-body">
                    <p class="card-text">Категория: {{ object.category }}</p>
                    <p class="card-text">{{ object.description }}</p>
                    <p class="card-text">Цена: {{ object.price }}$</p>
                </div>
                <!--        <img src="/media/{{ object.image }}" style="max-width: 100%; height: auto;" class="card-img-bottom">-->
                <img src="{{ object.image|mymedia }}" style="max-width: 100%; height: auto;" class="card-img-bottom">
                <div class="card-footer">
                    <small class="d-block mb-3 text-muted">{{ object.owner_product|default:"Создатель не известен" }}</small>
                    {% if perms.catalog.change_product %}
                        <a class="btn btn-lg btn-primary" href="{% url 'catalog:product_edit' object.pk %}">Редактировать
                        продукт</a>
                    {% endif %}
                    {% if perms.catalog.delete_product %}
                        <a class="btn btn-lg btn-danger" href="{% url 'catalog:product_delete' object.pk %}">Удалить продукт</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Все наши продукты</h1>
    <p class="lead">Skystore - это отличный вариант приобретения плагинов, проектов и других IT-услуг.</p>
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-left">
    {% if perms.catalog.add_product %}
        <a class="btn btn-lg btn-primary" style="margin-left: 102px;" href="{% url 'catalog:product_create' %}">Добавить продукт</a>
    {% endif %}
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header" style="height: 75px;">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body d-flex flex-column" style="height: 180px;">
                    <h1 class="card-title pricing-card-title">{{ object.price }}$</h1>
                    <div class="mt-auto">
                        <p class="card-title pricing-card-title" style="text-align: left;">{{ object.description|slice:":100" }}...</p>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="mt-auto">
                        <div class="card-text">
<!--                            Именованная обратная связь и перебор всех версий-->
                            {% for version in object.versions.all %}
                                {% if version.is_active %}
                                    {{ version.name }}
                                    {{ version.version_number }}
                                {% endif %}
                             {% endfor %}
                        </div>
                        <a href="{% url 'catalog:product_item' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Выбрать</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}